# Generated by Django 3.2.4 on 2022-09-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codigocie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCodigoCie',
            fields=[
                ('id_codigo', models.IntegerField(blank=True, db_index=True)),
                ('codigo_cie', models.CharField(max_length=20, verbose_name='Código CIE-10')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical codigo cie',
                'db_table': 'audit_codigocie',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
